-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS public.farm_block_media (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 block_id TEXT NOT NULL,
 file_path TEXT NOT NULL,
 kind TEXT NOT NULL CHECK (kind IN ('image','video')),
 caption TEXT,
 size_bytes BIGINT,
 created_by UUID,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 CONSTRAINT uq_farm_block_media_path UNIQUE (block_id, file_path)
);

CREATE INDEX IF NOT EXISTS idx_farm_block_media_block_time
 ON public.farm_block_media (block_id, created_at DESC);

ALTER TABLE public.farm_block_media ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_farm_block_media ON public.farm_block_media
 FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY authenticated_insert_farm_block_media ON public.farm_block_media
 FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY authenticated_delete_farm_block_media ON public.farm_block_media
 FOR DELETE TO authenticated USING (true);

