-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 农田监测核心表：区块 / 检测读数 / 历史曲线
CREATE TABLE IF NOT EXISTS public.farm_blocks (
  id TEXT PRIMARY KEY,
  row_idx INTEGER NOT NULL,
  col_idx INTEGER NOT NULL,
  crop_id TEXT NOT NULL,
  area_mu NUMERIC(6, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sensor_readings (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  block_id TEXT NOT NULL REFERENCES public.farm_blocks(id) ON DELETE CASCADE,
  temp NUMERIC(6, 2) NOT NULL,
  humid NUMERIC(6, 2) NOT NULL,
  has_pest BOOLEAN NOT NULL DEFAULT FALSE,
  pest_code TEXT,
  pest_level TEXT,
  status TEXT NOT NULL DEFAULT 'normal',
  collected_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sensor_readings_block_time_idx
  ON public.sensor_readings (block_id, collected_at DESC);

CREATE TABLE IF NOT EXISTS public.reading_history (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  block_id TEXT NOT NULL REFERENCES public.farm_blocks(id) ON DELETE CASCADE,
  temp NUMERIC(6, 2) NOT NULL,
  humid NUMERIC(6, 2) NOT NULL,
  bucket_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS reading_history_block_bucket_idx
  ON public.reading_history (block_id, bucket_at DESC);

ALTER TABLE public.farm_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_farm_blocks ON public.farm_blocks
  FOR SELECT USING (true);

CREATE POLICY anon_select_sensor_readings ON public.sensor_readings
  FOR SELECT USING (true);

CREATE POLICY anon_select_reading_history ON public.reading_history
  FOR SELECT USING (true);

