-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 历史曲线重建：weather-tick 以 service_role 身份清理并重灌 reading_history，需要服务角色可用的写入策略
DROP POLICY IF EXISTS service_insert_reading_history ON public.reading_history;
DROP POLICY IF EXISTS service_delete_reading_history ON public.reading_history;
DROP POLICY IF EXISTS service_write_reading_history ON public.reading_history;

CREATE POLICY service_write_reading_history ON public.reading_history
 TO authenticated, service_role USING (true) WITH CHECK (true);

