-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 注册时自动创建 profiles；唯一管理账号（用户名 + 虚拟邮箱）
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, username, display_name, role_label)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'username', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data ->> 'display_name', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data ->> 'role_label'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

INSERT INTO auth.users (
  instance_id, id, aud, role, email,
  encrypted_password, email_confirmed_at,
  created_at, updated_at,
  confirmation_token, recovery_token,
  email_change_token_new, email_change,
  raw_app_meta_data, raw_user_meta_data,
  is_super_admin
)
SELECT v.*
FROM (VALUES
  ('00000000-0000-0000-0000-000000000000'::uuid, gen_random_uuid(), 'authenticated'::text, 'authenticated'::text,
   'admin@meoo.local'::text, crypt('admin123', gen_salt('bf')), NOW(), NOW(), NOW(),
   ''::text, ''::text, ''::text, ''::text,
   '{"provider":"email","providers":["email"]}'::jsonb,
   '{"username":"admin","display_name":"田间管理员","role_label":"农场主管"}'::jsonb, false)
) AS v(instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at,
       confirmation_token, recovery_token, email_change_token_new, email_change,
       raw_app_meta_data, raw_user_meta_data, is_super_admin)
WHERE NOT EXISTS (
  SELECT 1 FROM auth.users u WHERE u.email = v.email
);

