-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.farm_weather_daily ALTER COLUMN source SET DEFAULT 'open-meteo';
ALTER TABLE public.farm_weather_hourly ALTER COLUMN source SET DEFAULT 'open-meteo';

