-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 全田真实气象：逐日聚合（平均气温 / 最低最高气温 / 平均湿度）+ 逐时实况
CREATE TABLE IF NOT EXISTS public.farm_weather_daily (
  day_date DATE PRIMARY KEY,
  avg_temp NUMERIC(6, 2) NOT NULL,
  max_temp NUMERIC(6, 2) NOT NULL,
  min_temp NUMERIC(6, 2) NOT NULL,
  avg_humid NUMERIC(6, 2) NOT NULL,
  source TEXT NOT NULL DEFAULT 'wttr.in',
  station TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.farm_weather_hourly (
  bucket_at TIMESTAMPTZ PRIMARY KEY,
  temp NUMERIC(6, 2) NOT NULL,
  humid NUMERIC(6, 2) NOT NULL,
  source TEXT NOT NULL DEFAULT 'wttr.in',
  station TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS farm_weather_daily_date_idx
  ON public.farm_weather_daily (day_date DESC);

CREATE INDEX IF NOT EXISTS farm_weather_hourly_bucket_idx
  ON public.farm_weather_hourly (bucket_at DESC);

ALTER TABLE public.farm_weather_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farm_weather_hourly ENABLE ROW LEVEL SECURITY;

-- 前端只读（含游客），写入统一由 weather-tick 以服务身份完成
DROP POLICY IF EXISTS anon_select_farm_weather_daily ON public.farm_weather_daily;
CREATE POLICY anon_select_farm_weather_daily ON public.farm_weather_daily
  FOR SELECT USING (true);

DROP POLICY IF EXISTS anon_select_farm_weather_hourly ON public.farm_weather_hourly;
CREATE POLICY anon_select_farm_weather_hourly ON public.farm_weather_hourly
  FOR SELECT USING (true);

-- 区块种植作物允许登录用户修改（仅经 update-block 云函数下发）
DROP POLICY IF EXISTS service_update_farm_blocks ON public.farm_blocks;
CREATE POLICY service_update_farm_blocks ON public.farm_blocks
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

