-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


INSERT INTO storage.buckets (id, name, public)
VALUES (gen_random_uuid(), 'farm-media', true);

CREATE POLICY clients_select_farm_media_bucket ON storage.buckets
FOR SELECT TO anon, authenticated USING (name = 'farm-media');

CREATE POLICY anon_select_farm_media_objects ON storage.objects
FOR SELECT TO anon, authenticated
USING (bucket_id = (SELECT id FROM storage.buckets WHERE name = 'farm-media'));

CREATE POLICY authenticated_insert_farm_media_objects ON storage.objects
FOR INSERT TO authenticated
WITH CHECK (bucket_id = (SELECT id FROM storage.buckets WHERE name = 'farm-media'));

CREATE POLICY authenticated_delete_farm_media_objects ON storage.objects
FOR DELETE TO authenticated
USING (bucket_id = (SELECT id FROM storage.buckets WHERE name = 'farm-media'));

