-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 历史曲线重建：weather-tick 以 service_role 身份清理并重灌 reading_history，需要服务写入策略
ALTER TABLE public.reading_history FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS service_write_reading_history ON public.reading_history;
CREATE POLICY service_write_reading_history ON public.reading_history
 TO authenticated USING (true) WITH CHECK (true);

