-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS service_insert_sensor_readings ON public.sensor_readings;
CREATE POLICY service_insert_sensor_readings ON public.sensor_readings
 FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS service_update_sensor_readings ON public.sensor_readings;
CREATE POLICY service_update_sensor_readings ON public.sensor_readings
 FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS service_delete_sensor_readings ON public.sensor_readings;
CREATE POLICY service_delete_sensor_readings ON public.sensor_readings
 FOR DELETE TO authenticated USING (true);

DROP POLICY IF EXISTS service_insert_reading_history ON public.reading_history;
CREATE POLICY service_insert_reading_history ON public.reading_history
 FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS service_delete_reading_history ON public.reading_history;
CREATE POLICY service_delete_reading_history ON public.reading_history
 FOR DELETE TO authenticated USING (true);

DROP POLICY IF EXISTS service_insert_alerts ON public.alerts;
CREATE POLICY service_insert_alerts ON public.alerts
 FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS service_update_alerts ON public.alerts;
CREATE POLICY service_update_alerts ON public.alerts
 FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS service_delete_alerts ON public.alerts;
CREATE POLICY service_delete_alerts ON public.alerts
 FOR DELETE TO authenticated USING (true);

