// ============================================
// 此文件由 Meoo Cloud 自动生成，请勿修改
// This file is auto-generated by Meoo Cloud, DO NOT MODIFY
// ============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      alerts: {
        Row: {
          block_id: string
          created_at: string
          id: string
          message: string
          resolved: boolean
          severity: string
          type: string
        }
        Insert: {
          block_id: string
          created_at?: string
          id?: string
          message: string
          resolved?: boolean
          severity: string
          type: string
        }
        Update: {
          block_id?: string
          created_at?: string
          id?: string
          message?: string
          resolved?: boolean
          severity?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "alerts_block_id_fkey"
            columns: ["block_id"]
            referencedRelation: "farm_blocks"
            referencedColumns: ["id"]
          },
        ]
      }
      farm_block_media: {
        Row: {
          block_id: string
          caption: string | null
          created_at: string
          created_by: string | null
          file_path: string
          id: string
          kind: string
          size_bytes: number | null
        }
        Insert: {
          block_id: string
          caption?: string | null
          created_at?: string
          created_by?: string | null
          file_path: string
          id?: string
          kind: string
          size_bytes?: number | null
        }
        Update: {
          block_id?: string
          caption?: string | null
          created_at?: string
          created_by?: string | null
          file_path?: string
          id?: string
          kind?: string
          size_bytes?: number | null
        }
        Relationships: []
      }
      farm_blocks: {
        Row: {
          area_mu: number
          col_idx: number
          created_at: string
          crop_id: string
          id: string
          row_idx: number
        }
        Insert: {
          area_mu?: number
          col_idx: number
          created_at?: string
          crop_id: string
          id: string
          row_idx: number
        }
        Update: {
          area_mu?: number
          col_idx?: number
          created_at?: string
          crop_id?: string
          id?: string
          row_idx?: number
        }
        Relationships: []
      }
      farm_weather_daily: {
        Row: {
          avg_humid: number
          avg_temp: number
          day_date: string
          max_temp: number
          min_temp: number
          source: string
          station: string
          updated_at: string
        }
        Insert: {
          avg_humid: number
          avg_temp: number
          day_date: string
          max_temp: number
          min_temp: number
          source?: string
          station?: string
          updated_at?: string
        }
        Update: {
          avg_humid?: number
          avg_temp?: number
          day_date?: string
          max_temp?: number
          min_temp?: number
          source?: string
          station?: string
          updated_at?: string
        }
        Relationships: []
      }
      farm_weather_hourly: {
        Row: {
          bucket_at: string
          humid: number
          source: string
          station: string
          temp: number
          updated_at: string
        }
        Insert: {
          bucket_at: string
          humid: number
          source?: string
          station?: string
          temp: number
          updated_at?: string
        }
        Update: {
          bucket_at?: string
          humid?: number
          source?: string
          station?: string
          temp?: number
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string | null
          id: string
          role_label: string | null
          username: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          id: string
          role_label?: string | null
          username: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          role_label?: string | null
          username?: string
        }
        Relationships: []
      }
      reading_history: {
        Row: {
          block_id: string
          bucket_at: string
          humid: number
          id: number
          temp: number
        }
        Insert: {
          block_id: string
          bucket_at: string
          humid: number
          id?: never
          temp: number
        }
        Update: {
          block_id?: string
          bucket_at?: string
          humid?: number
          id?: never
          temp?: number
        }
        Relationships: [
          {
            foreignKeyName: "reading_history_block_id_fkey"
            columns: ["block_id"]
            referencedRelation: "farm_blocks"
            referencedColumns: ["id"]
          },
        ]
      }
      sensor_readings: {
        Row: {
          block_id: string
          collected_at: string
          has_pest: boolean
          humid: number
          id: number
          pest_code: string | null
          pest_level: string | null
          status: string
          temp: number
        }
        Insert: {
          block_id: string
          collected_at?: string
          has_pest?: boolean
          humid: number
          id?: never
          pest_code?: string | null
          pest_level?: string | null
          status?: string
          temp: number
        }
        Update: {
          block_id?: string
          collected_at?: string
          has_pest?: boolean
          humid?: number
          id?: never
          pest_code?: string | null
          pest_level?: string | null
          status?: string
          temp?: number
        }
        Relationships: [
          {
            foreignKeyName: "sensor_readings_block_id_fkey"
            columns: ["block_id"]
            referencedRelation: "farm_blocks"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
