/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutDecisionRouteImport } from './routes/_layout.decision'
import { Route as LayoutStatsRouteImport } from './routes/_layout.stats'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDecisionRoute = LayoutDecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStatsRoute = LayoutStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/decision': typeof LayoutDecisionRoute
  '/stats': typeof LayoutStatsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/decision': typeof LayoutDecisionRoute
  '/stats': typeof LayoutStatsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/decision': typeof LayoutDecisionRoute
  '/_layout/stats': typeof LayoutStatsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/decision' | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/decision' | '/stats' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/decision'
    | '/_layout/stats'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/decision': {
      id: '/_layout/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof LayoutDecisionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stats': {
      id: '/_layout/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof LayoutStatsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDecisionRoute: typeof LayoutDecisionRoute
  LayoutStatsRoute: typeof LayoutStatsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDecisionRoute: LayoutDecisionRoute,
  LayoutStatsRoute: LayoutStatsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
